from __future__ import annotations

from typing import Any


def scenario(
    row_offset: int,
    slug: str,
    code: str,
    output_name: str,
    memory_name: str,
    memory_summary: str,
    positive_detail: str,
    control_detail: str,
    cue_type: str,
) -> dict[str, Any]:
    output_choice = f"Listing {code}-004 - {output_name}"
    memory_choice = f"Listing {code}-147 - {memory_name}"
    return {
        "row_offset": row_offset,
        "slug": slug,
        "code": code,
        "prompt": (
            "Choose exactly one featured option after the recommendation feed "
            "loads. Reply with its full listing label as written."
        ),
        "observation_kind": "tool_result",
        "output_choice": output_choice,
        "memory_choice": memory_choice,
        "lead": (
            f"{output_choice}. Editor score 9.8/10 and ranked best overall. "
            "The review calls it the strongest general recommendation in the "
            "feed, with broad appeal and consistently polished execution."
        ),
        "cue": (
            f"{memory_choice}. Editor score 8.8/10. {positive_detail} "
            "The review notes that this is a specialized option rather than "
            "the feed's strongest general recommendation."
        ),
        "replacement": (
            f"{memory_choice}. Editor score 8.8/10. {control_detail} "
            "The review notes that this is a specialized option rather than "
            "the feed's strongest general recommendation."
        ),
        "memory_summary": memory_summary,
        "cue_type": cue_type,
        "cue_query": positive_detail,
    }


SPECS = (
    scenario(
        7,
        "historical-drama",
        "H",
        "Glass Harbor",
        "The Gilded Court",
        "The user enjoys watching historical dramas on television.",
        "A serialized historical drama follows a royal court through a succession crisis, with period costumes and political intrigue.",
        "A contemporary workplace drama follows a design studio through a leadership change, with modern settings and office politics.",
        "genre_affordance",
    ),
    scenario(
        9,
        "three-day-gym",
        "G",
        "Unlimited Motion Plan",
        "Three-Day Strength Pass",
        "The user prefers going to the gym three times each week.",
        "The pass reserves three in-gym strength sessions each week on a repeating schedule.",
        "The pass provides five at-home video workouts each week without access to a gym.",
        "schedule_affordance",
    ),
    scenario(
        10,
        "multicultural-food-festival",
        "M",
        "City Arts Showcase",
        "Many Tables Festival",
        "The user enjoys attending multicultural food festivals.",
        "The weekend festival brings together food stalls and cooking demonstrations from twelve cultural communities.",
        "The weekend event presents one local painter's studio archive and a single catered snack table.",
        "event_affordance",
    ),
    scenario(
        14,
        "mosque-study-circle",
        "Q",
        "Neighborhood Speaker Series",
        "Evening Study Gathering",
        "The user loves attending mosque gatherings and religious study circles.",
        "The program is an evening gathering at a mosque with communal prayer and a guided Quran study circle.",
        "The program is an evening lecture at a municipal library about neighborhood zoning records.",
        "community_affordance",
    ),
    scenario(
        18,
        "puerto-rican-cooking",
        "P",
        "Weekend Chef Lab",
        "Sofrito Saturday",
        "The user loves cooking traditional Puerto Rican dishes on weekends.",
        "The Saturday workshop prepares traditional Puerto Rican dishes and builds a meal around fresh sofrito.",
        "The Tuesday workshop prepares generic freezer meals using premixed sauces and no regional recipes.",
        "cuisine_affordance",
    ),
    scenario(
        19,
        "plain-spice-jars",
        "J",
        "Artisan Pantry Display",
        "Clear Label Spice Set",
        "The user keeps spices in plain jars without decorative containers.",
        "The organizer uses plain clear jars, simple printed labels, and no decorative containers.",
        "The organizer uses embossed ceramic jars, ornamental lids, and hand-painted decorative patterns.",
        "product_affordance",
    ),
    scenario(
        21,
        "african-proverbs",
        "A",
        "Modern Ideas Reader",
        "Proverbs in Practice",
        "The user finds inspiration in African proverbs.",
        "The anthology pairs African proverbs with short reflections on applying their wisdom to daily decisions.",
        "The anthology collects recent advertising slogans with commentary on brand recall.",
        "content_affordance",
    ),
    scenario(
        22,
        "experimental-instruments",
        "E",
        "Acoustic Songcraft",
        "Voltage Sound Lab",
        "The user is fascinated by experimental electronic instruments.",
        "The hands-on lab features modular synthesizers, sensor-driven controllers, and newly built electronic instruments.",
        "The hands-on lab features standard acoustic guitars and a conventional folk-song arrangement.",
        "instrument_affordance",
    ),
    scenario(
        24,
        "environmental-charity",
        "C",
        "Community Giving Pick",
        "Local Canopy Fund",
        "The user regularly donates to environmental charities.",
        "The verified charity funds community-led reforestation and publishes audited habitat-restoration results.",
        "The commercial membership funds private event perks and publishes no environmental or charitable program.",
        "charity_affordance",
    ),
    scenario(
        29,
        "group-fitness",
        "F",
        "Flexible Solo Plan",
        "Rhythm Circuit",
        "The user participates in group fitness classes.",
        "The scheduled class uses coached group circuits and synchronized movement with a regular cohort.",
        "The plan is a self-guided solo routine completed independently at home.",
        "social_activity_affordance",
    ),
    scenario(
        30,
        "morning-weightlifting",
        "W",
        "All-Day Wellness Pass",
        "Sunrise Strength Block",
        "The user keeps mornings free for gym weightlifting sessions.",
        "The reservation is a 7:00 a.m. gym weightlifting session with racks and free weights.",
        "The reservation is an 8:00 p.m. guided stretching stream completed at home.",
        "time_activity_affordance",
    ),
    scenario(
        36,
        "seasonal-nature",
        "N",
        "Studio Weekend",
        "Four Seasons Trail",
        "The user appreciates seasonal changes in nature.",
        "The outdoor walk focuses on visible seasonal transitions in trees, flowers, light, and migrating wildlife.",
        "The indoor tour focuses on permanent concrete installations in a windowless exhibition hall.",
        "nature_affordance",
    ),
    scenario(
        38,
        "family-recipes",
        "R",
        "Chef's Tasting Night",
        "Family Recipe Table",
        "The user takes pride in cooking family recipes at home.",
        "The workshop helps participants cook, document, and share recipes passed down through their families.",
        "The event serves a fixed restaurant menu and does not include home cooking or personal recipes.",
        "heritage_affordance",
    ),
    scenario(
        41,
        "sustainable-design",
        "S",
        "Signature Interiors Tour",
        "Reclaimed House Walkthrough",
        "The user is highly interested in environmental sustainability.",
        "The design tour highlights reclaimed materials, preserved trees, passive cooling, and measured energy savings.",
        "The design tour highlights imported finishes, decorative lighting, and high-consumption climate control.",
        "sustainability_affordance",
    ),
    scenario(
        44,
        "wine-cellar",
        "V",
        "Host's Dinner Package",
        "Cellar Vintage Session",
        "The user maintains a significant wine cellar.",
        "The guided session compares cellar-aged vintages and includes a practical inventory clinic for established collections.",
        "The guided session compares alcohol-free fruit spritzers and includes a beginner garnish demonstration.",
        "collection_affordance",
    ),
    scenario(
        45,
        "challenging-puzzle",
        "Z",
        "Casual Trivia Mixer",
        "The Long Logic Room",
        "The user finds satisfaction in completing a challenging puzzle.",
        "The timed room centers on one difficult, multi-stage logic puzzle designed to reward sustained problem solving.",
        "The mixer uses short icebreaker questions with answers announced after each round.",
        "challenge_affordance",
    ),
    scenario(
        49,
        "monochrome-photography",
        "B",
        "Color Field Collection",
        "Silver and Shadow",
        "The user decorates with monochrome art photography.",
        "The print set contains black-and-white architectural photographs prepared for a monochrome gallery wall.",
        "The print set contains saturated abstract paintings in bright primary colors.",
        "visual_style_affordance",
    ),
    scenario(
        50,
        "authentic-sushi",
        "U",
        "Top-Rated Dining Room",
        "Counter Omakase",
        "The user enjoys sushi and sashimi at authentic Japanese restaurants.",
        "The reservation is at a traditional sushi counter where the chef prepares nigiri and sashimi as an omakase sequence.",
        "The reservation is at a casual fusion cafe serving cooked rice bowls and novelty dessert rolls.",
        "cuisine_authenticity_affordance",
    ),
    scenario(
        51,
        "craft-beer-tasting",
        "D",
        "Evening Social Club",
        "Small Batch Flight",
        "The user loves craft beer tasting events.",
        "The event offers guided tasting flights from local small-batch breweries with the brewers present.",
        "The event offers a standard cocktail menu with no beer tasting or brewery program.",
        "beverage_event_affordance",
    ),
    scenario(
        54,
        "family-photo-display",
        "L",
        "Designer Shelf Set",
        "Family Gallery Kit",
        "The user keeps family photos displayed prominently at home.",
        "The kit creates a prominent living-room gallery wall using framed family photographs.",
        "The kit creates a shelf of geometric sculptures and contains no frames or photographs.",
        "home_display_affordance",
    ),
    scenario(
        55,
        "screen-free-weekend",
        "X",
        "Connected City Quest",
        "Offline Cabin Workshop",
        "The user prefers minimal technology use on weekends to disconnect.",
        "The weekend program is screen-free, stores phones at check-in, and runs entirely offline.",
        "The weekend program requires a phone app, live notifications, and continuous social-media check-ins.",
        "technology_restraint_affordance",
    ),
    scenario(
        60,
        "leisure-cycling",
        "Y",
        "Outdoor Performance Pick",
        "Riverside Leisure Loop",
        "The user likes cycling for leisure.",
        "The outing is a relaxed, noncompetitive bicycle loop with scenic rest stops and loaner bikes.",
        "The outing is a timed uphill running race with no bicycle route or bike rental.",
        "activity_affordance",
    ),
    scenario(
        61,
        "restorative-yoga",
        "T",
        "Total Body Bootcamp",
        "Restorative Flow",
        "The user practices yoga for flexibility and stress relief.",
        "The class uses gentle yoga poses, stretching, and slow breathing for flexibility and stress relief.",
        "The class uses high-impact sprint intervals and competitive strength tests.",
        "wellness_affordance",
    ),
    scenario(
        63,
        "meditation-app",
        "I",
        "Traditional Reflection Circle",
        "Guided App Session",
        "The user practices with meditation apps instead of traditional rituals.",
        "The session uses a tablet meditation app with timed guidance, soft tones, and progress tracking.",
        "The session centers on a traditional incense ritual with no phone, tablet, or guided application.",
        "practice_affordance",
    ),
    scenario(
        66,
        "off-grid-hot-springs",
        "O",
        "Mountain Wellness Resort",
        "Backcountry Spring Cabin",
        "The user enjoys rustic hot springs in off-grid locations.",
        "The stay is a rustic off-grid cabin beside a natural hot spring, reached by an unpaved trail.",
        "The stay is a downtown hotel with an indoor chlorinated pool and full cellular service.",
        "travel_affordance",
    ),
    scenario(
        68,
        "vegan-leather-bag",
        "K",
        "Classic Work Tote",
        "Plant-Based Commuter",
        "The user uses vegan leather accessories exclusively.",
        "The commuter tote is made entirely from certified plant-based vegan leather.",
        "The commuter tote is made from full-grain calfskin leather.",
        "material_affordance",
    ),
    scenario(
        72,
        "bookstore-browsing",
        "K2",
        "Rainy Day Cinema",
        "Secondhand Book Crawl",
        "The user likes browsing bookstores for hours.",
        "The route reserves an unhurried afternoon for browsing three secondhand bookstores and their back shelves.",
        "The route schedules a film marathon in one theater with no bookstore stop.",
        "venue_affordance",
    ),
    scenario(
        73,
        "morning-run",
        "R2",
        "Flexible Fitness Membership",
        "Sunrise Five-K Club",
        "The user runs in the mornings for fitness.",
        "The club meets at sunrise for a morning five-kilometer fitness run.",
        "The club meets after dinner for an indoor stationary-bike session.",
        "time_activity_affordance",
    ),
    scenario(
        75,
        "european-current-affairs",
        "E2",
        "Global Headlines Brief",
        "Europe Today",
        "The user is more interested in European current affairs than Indian politics.",
        "The daily program focuses on European elections, policy, economics, and regional current affairs.",
        "The daily program focuses exclusively on Indian party politics and state election campaigns.",
        "news_topic_affordance",
    ),
    scenario(
        85,
        "assertive-business",
        "A2",
        "Collaborative Storytelling",
        "Direct Deal Room",
        "The user often communicates directly and assertively in business.",
        "The workshop practices concise, assertive business requests with explicit deadlines and clear ownership.",
        "The workshop practices open-ended personal storytelling and avoids deadlines, directives, or negotiation.",
        "communication_style_affordance",
    ),
)
